# Supabase project configuration
# Edge Function settings

[functions]

[functions."iyzico-callback"]
verify_jwt = false

[functions."admin-update-order"]
verify_jwt = false

[functions."admin-order-inspect"]
verify_jwt = false

[functions."admin-orders-latest"]
verify_jwt = false

[functions."admin-iyzico-reconcile"]
verify_jwt = false

[functions."shipping-webhook"]
verify_jwt = false

[functions."shipping-status"]
verify_jwt = false
