"use client"
/** @generated by VentHub-Factory - Assembler **/
import React, { Suspense } from 'react'

interface PartConfig {
    name: string
    component: React.ElementType
    position?: [number, number, number]
    rotation?: [number, number, number]
    scale?: [number, number, number]
    props?: Record<string, unknown>
}

interface BluePrint {
    slug: string
    scale?: number
    parts: PartConfig[]
}

interface AssemblerProps {
    blueprint: BluePrint
    explode?: number
    onPartClick?: (partName: string) => void
    selectedPart?: string | null
    isolatedPart?: string | null
    hiddenParts?: string[]
}

export const Assembler: React.FC<AssemblerProps> = ({ 
    blueprint, 
    explode = 0,
    onPartClick,
    selectedPart,
    isolatedPart,
    hiddenParts = []
}) => {
    return (
        <group scale={blueprint.scale || 1}>
            {blueprint.parts.map((part, index) => {
                const Component = part.component
                
                // Patlatılmış görünüm (Explode) mantığı
                // Basitçe parçaları merkezden uzaklaştırır
                const explodeOffset: [number, number, number] = [
                    (part.position?.[0] || 0) * (1 + explode * 2),
                    (part.position?.[1] || 0) * (1 + explode * 2),
                    (part.position?.[2] || 0) * (1 + explode * 2)
                ]

                return (
                    <group 
                        key={`${part.name}-${index}`} 
                        position={explodeOffset}
                        rotation={part.rotation || [0, 0, 0]}
                        scale={part.scale || [1, 1, 1]}
                    >
                        <Suspense fallback={null}>
                            <Component 
                                {...(part.props || {})} 
                                explode={explode}
                                isSelected={selectedPart === part.name}
                                isIsolated={isolatedPart === part.name || isolatedPart === null}
                                isHidden={hiddenParts.includes(part.name)}
                                onClick={() => onPartClick?.(part.name)}
                            />
                        </Suspense>
                    </group>
                )
            })}
        </group>
    )
}
