"use client"
/** @generated by VentHub-Factory - Assembler **/
import React from 'react'
import { Assembler } from './Assembler'
import { MainChassis } from './parts/MainChassis'
import { GreenClamps } from './parts/GreenClamps'
import { BoxAndBase } from './parts/BoxAndBase'
import { InternalFanRotor } from './parts/InternalFanRotor'

/**
 * VorticeLineoModel - High-fidelity assembly of the Vortice Lineo 100 fan.
 * Coordinating professional geometries for the housing, clamps, terminal box, and impeller.
 */
export const VorticeLineoModel: React.FC<{
    explode?: number
    onPartClick?: (partName: string) => void
    selectedPart?: string | null
    isolatedPart?: string | null
    hiddenParts?: string[]
}> = ({ 
    explode = 0,
    onPartClick,
    selectedPart,
    isolatedPart,
    hiddenParts = []
}) => {
    const blueprint = {
        slug: "vortice-lineo",
        scale: 1.0,
        parts: [
            {
                name: "Chassis",
                component: MainChassis,
                position: [0, 0, 0] as [number, number, number],
                rotation: [0, 0, 0] as [number, number, number] // Rotation now handled inside MainChassis group
            },
            {
                name: "Clamps",
                component: GreenClamps,
                position: [0, 0, 0] as [number, number, number]
            },
            {
                name: "Details",
                component: BoxAndBase,
                position: [0, 0, 0] as [number, number, number]
            },
            {
                name: "Rotor",
                component: InternalFanRotor,
                position: [0, 0, 0] as [number, number, number],
                rotation: [0, 0, Math.PI / 2] as [number, number, number] // Align rotor axis with horizontal housing
            }
        ]
    }

    return (
        <group rotation={[0, 0, 0]}>
            <Assembler 
                blueprint={blueprint} 
                explode={explode} 
                onPartClick={onPartClick}
                selectedPart={selectedPart}
                isolatedPart={isolatedPart}
                hiddenParts={hiddenParts}
            />
        </group>
    )
}

export default VorticeLineoModel
