/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
/** @generated by VentHub-Worker-D **/
import React from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { Utensils, Factory, Car, Building2, ArrowRight } from 'lucide-react'

interface ApplicationCard {
    id: string
    title: string
    description: string
    icon: React.ReactNode
    image: string
    href: string
}

const applications: ApplicationCard[] = [
    {
        id: 'restoran',
        title: 'Restoran Uygulamaları',
        description: 'Konforlu hava kalitesi ve enerji tasarrufu.',
        icon: <Utensils size={20} />,
        image: '/images/bento/kitchen.jpg',
        href: '/category/hava-perdeleri'
    },
    {
        id: 'fabrika',
        title: 'Fabrika ve Üretim',
        description: 'Zorlu endüstriyel ortamlar için çözümler.',
        icon: <Factory size={20} />,
        image: '/images/bento/smoke.jpg',
        href: '/category/fanlar'
    },
    {
        id: 'otopark',
        title: 'Otopark Havalandırma',
        description: 'Güvenli ve temiz hava sirkülasyonu.',
        icon: <Car size={20} />,
        image: '/images/bento/parking.jpg',
        href: '/category/fanlar'
    },
    {
        id: 'ofis',
        title: 'Ofis ve Ticari Binalar',
        description: 'Verimli çalışma ortamları için ideal.',
        icon: <Building2 size={20} />,
        image: '/images/bento/hvac.jpg',
        href: '/category/isi-geri-kazanim-cihazlari'
    }
]

/**
 * Application area cards for Products Hub
 * Optimized with Next.js Image and refined layout for high-performance e-commerce
 */
const ApplicationCards: React.FC = () => {
    return (
        <section className="py-8">
            <h2 className="text-xl font-bold text-industrial-gray mb-6 px-1">Uygulamaya Göre Çözümler</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {applications.map((app) => (
                    <Link
                        key={app.id}
                        href={app.href}
                        className="group flex flex-col bg-white border border-gray-100 rounded-2xl overflow-hidden shadow-sm hover:shadow-xl hover:border-primary-navy/20 transition-all duration-300"
                    >
                        {/* Image Container with Next/Image */}
                        <div className="relative h-40 w-full overflow-hidden bg-gray-100">
                            <Image
                                src={app.image}
                                alt={app.title}
                                fill
                                sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw"
                                className="object-cover group-hover:scale-110 transition-transform duration-500"
                                priority={app.id === 'restoran'} // Priority for the first item
                            />
                            {/* Overlay for icon */}
                            <div className="absolute top-4 left-4 w-10 h-10 rounded-xl bg-white/90 backdrop-blur-sm flex items-center justify-center text-primary-navy shadow-md z-10 transition-transform group-hover:scale-105">
                                {app.icon}
                            </div>
                        </div>

                        {/* Content */}
                        <div className="p-5 flex flex-col flex-1">
                            <h3 className="font-bold text-industrial-gray text-base mb-2 group-hover:text-primary-navy transition-colors">
                                {app.title}
                            </h3>

                            <p className="text-sm text-gray-500 leading-relaxed mb-4 line-clamp-2">
                                {app.description}
                            </p>

                            <div className="mt-auto pt-2 flex items-center gap-2 text-sm font-semibold text-primary-navy opacity-80 group-hover:opacity-100 transition-opacity">
                                <span>Detayları Gör</span>
                                <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
                            </div>
                        </div>
                    </Link>
                ))}
            </div>
        </section>
    )
}

export default ApplicationCards
