/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
/** @generated by VentHub-Worker-C **/
import React from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { ChevronRight } from 'lucide-react'

/**
 * Premium category showcase cards - Optimized with Next.js Image
 * Using high-quality isometric product renders
 */
const CategoryShowcaseCards: React.FC = () => {
    return (
        <section className="py-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                {/* Hava Perdeleri Card */}
                <Link
                    href="/category/air-curtains"
                    className="group relative flex flex-col rounded-2xl overflow-hidden border border-slate-600/50 bg-gradient-to-b from-slate-700/80 via-slate-800 to-slate-900 hover:border-slate-400/50 transition-all duration-300 hover:shadow-2xl"
                >
                    <div className="p-6 pb-2 text-center">
                        {/* Icon - Door with air flow lines */}
                        <div className="flex justify-center mb-4">
                            <svg width="56" height="56" viewBox="0 0 56 56" fill="none" className="text-cyan-400">
                                <rect x="12" y="8" width="20" height="40" rx="2" stroke="currentColor" strokeWidth="2" fill="none" />
                                <rect x="26" y="26" width="3" height="6" rx="1" fill="currentColor" />
                                <path d="M36 16 L48 16" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                                <path d="M36 22 L52 22" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                                <path d="M36 28 L48 28" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                                <path d="M36 34 L44 34" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                            </svg>
                        </div>
                        <h3 className="text-lg font-bold text-white mb-2">Hava Perdeleri</h3>
                        <p className="text-sm text-gray-400 leading-relaxed">
                            Ticari ve endüstriyel alanlar için enerji verimli hava bariyerleri.
                        </p>
                    </div>

                    {/* Product Image - Air Curtain Unit */}
                    <div className="flex-1 flex items-center justify-center px-6 py-4 min-h-[140px] relative">
                        <Image 
                            src="/images/products/isometric-air-curtain.png"
                            alt="Hava Perdesi"
                            width={220}
                            height={120}
                            className="object-contain group-hover:scale-105 transition-transform duration-500 drop-shadow-[0_10px_10px_rgba(0,0,0,0.5)]"
                        />
                    </div>

                    {/* CTA Button */}
                    <div className="p-5 pt-2">
                        <div className="flex items-center justify-center gap-2 py-2.5 px-5 bg-white/5 border border-white/20 rounded-full text-white font-medium text-sm hover:bg-white/10 transition-all">
                            <span>Keşfet</span>
                            <ChevronRight size={16} />
                        </div>
                    </div>
                </Link>

                {/* Endüstriyel Fanlar Card */}
                <Link
                    href="/category/fans"
                    className="group relative flex flex-col rounded-2xl overflow-hidden border border-slate-600/50 bg-gradient-to-b from-slate-700/80 via-slate-800 to-slate-900 hover:border-slate-400/50 transition-all duration-300 hover:shadow-2xl"
                >
                    <div className="p-6 pb-2 text-center">
                        {/* Icon - Fan Symbol */}
                        <div className="flex justify-center mb-4">
                            <svg width="56" height="56" viewBox="0 0 56 56" fill="none" className="text-cyan-400">
                                <circle cx="28" cy="28" r="20" stroke="currentColor" strokeWidth="2" fill="none" />
                                <circle cx="28" cy="28" r="4" fill="currentColor" />
                                <path d="M28 8 C32 14 32 22 28 24 C24 22 24 14 28 8" fill="currentColor" opacity="0.7" />
                                <path d="M48 28 C42 32 34 32 32 28 C34 24 42 24 48 28" fill="currentColor" opacity="0.7" />
                                <path d="M28 48 C24 42 24 34 28 32 C32 34 32 42 28 48" fill="currentColor" opacity="0.7" />
                                <path d="M8 28 C14 24 22 24 24 28 C22 32 14 32 8 28" fill="currentColor" opacity="0.7" />
                            </svg>
                        </div>
                        <h3 className="text-lg font-bold text-white mb-2">Endüstriyel & Sessiz Fanlar</h3>
                        <p className="text-sm text-gray-400 leading-relaxed">
                            Aero-akustik optimizasyonlu, yüksek performanslı kanal tipi karma akışlı fanlar.
                        </p>
                    </div>

                    {/* Product Image - Premium Lineo */}
                    <div className="flex-1 flex items-center justify-center px-6 py-4 min-h-[140px] relative">
                        <Image 
                            src="/images/vortice_lineo_futuristic.png"
                            alt="Endüstriyel Fan"
                            width={180}
                            height={160}
                            className="object-contain group-hover:scale-105 transition-transform duration-500 drop-shadow-[0_10px_10px_rgba(0,0,0,0.5)]"
                        />
                    </div>

                    {/* CTA Button */}
                    <div className="p-5 pt-2">
                        <div className="flex items-center justify-center gap-2 py-2.5 px-5 bg-white/5 border border-white/20 rounded-full text-white font-medium text-sm hover:bg-white/10 transition-all">
                            <span>Keşfet</span>
                            <ChevronRight size={16} />
                        </div>
                    </div>
                </Link>

                {/* Isı Geri Kazanım Card */}
                <Link
                    href="/category/heat-recovery-units"
                    className="group relative flex flex-col rounded-2xl overflow-hidden border border-slate-600/50 bg-gradient-to-b from-slate-700/80 via-slate-800 to-slate-900 hover:border-slate-400/50 transition-all duration-300 hover:shadow-2xl"
                >
                    <div className="p-6 pb-2 text-center">
                        {/* Icon - Heat Exchange Arrows */}
                        <div className="flex justify-center mb-4">
                            <svg width="56" height="56" viewBox="0 0 56 56" fill="none" className="text-cyan-400">
                                <path d="M8 20 L28 20" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                                <path d="M20 14 L28 20 L20 26" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                                <path d="M48 36 L28 36" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                                <path d="M36 30 L28 36 L36 42" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                            </svg>
                        </div>
                        <h3 className="text-lg font-bold text-white mb-2">Isı Geri Kazanım</h3>
                        <p className="text-sm text-gray-400 leading-relaxed">
                            Enerji tasarrufu sağlayan gelişmiş ısı geri kazanım üniteleri.
                        </p>
                    </div>

                    {/* Product Image - HRV Unit */}
                    <div className="flex-1 flex items-center justify-center px-6 py-4 min-h-[140px] relative">
                        <Image 
                            src="/images/products/isometric-hrv.png"
                            alt="Isı Geri Kazanım Cihazı"
                            width={200}
                            height={120}
                            className="object-contain group-hover:scale-105 transition-transform duration-500 drop-shadow-[0_10px_10px_rgba(0,0,0,0.5)]"
                        />
                    </div>

                    {/* CTA Button */}
                    <div className="p-5 pt-2">
                        <div className="flex items-center justify-center gap-2 py-2.5 px-5 bg-white/5 border border-white/20 rounded-full text-white font-medium text-sm hover:bg-white/10 transition-all">
                            <span>Keşfet</span>
                            <ChevronRight size={16} />
                        </div>
                    </div>
                </Link>
            </div>
        </section>
    )
}

export default CategoryShowcaseCards
