/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
/** @generated by VentHub-Worker-A **/
'use client'

import React, { useRef, useState, useMemo, Suspense } from 'react'
import { Canvas, useFrame, useThree, ThreeEvent } from '@react-three/fiber'
import { 
    Environment, 
    Float, 
    Sparkles, 
    Text, 
    Image as DreiImage, 
    AdaptiveDpr, 
    AdaptiveEvents,
    Preload,
    Bvh
} from '@react-three/drei'
import * as THREE from 'three'
import { useRouter } from 'next/navigation'

interface ProductItem {
    id: string
    title: string
    image: string
}

interface InfiniteProductsShowcaseProps {
    items: ProductItem[]
}

/**
 * Optimized Image Loader helper
 * Mimics next/image optimization for Three.js textures
 */
const getOptimizedImageUrl = (url: string, width = 400) => {
    if (!url) return url
    if (url.startsWith('http') && url.includes('supabase')) {
        const base = url.split('?')[0]
        const renderUrl = base.includes('/object/') ? base.replace('/object/', '/render/image/') : base
        return `${renderUrl}?width=${width}&quality=75&format=webp`
    }
    return url
}

/**
 * Individual Product Card with Image and Title
 * Optimized using drei/Image and improved calculations
 */
const ProductCard: React.FC<{
    item: ProductItem
    index: number
    total: number
    gap: number
    scrollOffset: React.MutableRefObject<number>
    isPaused: boolean
    onHover: (hovering: boolean) => void
}> = ({ item, index, total, gap, scrollOffset, isPaused, onHover }) => {
    const groupRef = useRef<THREE.Group>(null)
    const imageRef = useRef<THREE.Mesh>(null)
    const router = useRouter()
    const [hovered, setHover] = useState(false)

    // Optimized URL for texture
    const optimizedUrl = useMemo(() => getOptimizedImageUrl(item.image), [item.image])

    const sphereWidth = total * gap

    useFrame((state, _delta) => {
        if (!groupRef.current) return

        // Smoother infinite scroll calculation
        const offset = scrollOffset.current
        let xPos = (index * gap) - (offset * sphereWidth)
        
        // Wrap around using modulo logic for performance
        xPos = ((xPos + sphereWidth / 2) % sphereWidth + sphereWidth) % sphereWidth - sphereWidth / 2

        groupRef.current.position.x = xPos
        groupRef.current.rotation.y = -xPos * 0.05

        // Hover zoom effect with lerp
        if (imageRef.current) {
            const targetScale = hovered ? 1.15 : 1.0
            imageRef.current.scale.x = THREE.MathUtils.lerp(imageRef.current.scale.x, targetScale, 0.15)
            imageRef.current.scale.y = THREE.MathUtils.lerp(imageRef.current.scale.y, targetScale, 0.15)
            
            // Pulse effect when hovered
            if (hovered && imageRef.current.material) {
                const mat = imageRef.current.material as THREE.MeshStandardMaterial
                mat.emissiveIntensity = THREE.MathUtils.lerp(
                    mat.emissiveIntensity || 0, 
                    0.5 + Math.sin(state.clock.elapsedTime * 4) * 0.2, 
                    0.1
                )
            }
        }
    })

    const handleClick = (e: ThreeEvent<MouseEvent>) => {
        e.stopPropagation()
        router.push(`/category/${item.id}`)
    }

    return (
        <group ref={groupRef}>
            <Float 
                speed={isPaused ? 0 : 1.5} 
                rotationIntensity={0.05} 
                floatIntensity={0.15} 
                floatingRange={[-0.02, 0.02]}
            >
                {/* Drei Image: High performance alternative to manual plane + texture */}
                <DreiImage
                    ref={imageRef}
                    url={optimizedUrl}
                    transparent
                    onClick={handleClick}
                    onPointerOver={() => { setHover(true); onHover(true); document.body.style.cursor = 'pointer' }}
                    onPointerOut={() => { setHover(false); onHover(false); document.body.style.cursor = 'auto' }}
                    scale={[3, 4]}
                    toneMapped={false}
                />

                {/* Optimized Hover glow ring */}
                {hovered && (
                    <mesh position={[0, 0, -0.05]}>
                        <ringGeometry args={[2.2, 2.3, 32]} />
                        <meshBasicMaterial color="#22d3ee" transparent opacity={0.3} />
                    </mesh>
                )}

                {/* Optimized Text Component */}
                <Text
                    position={[0, -2.4, 0.1]}
                    fontSize={0.24}
                    color={hovered ? '#22d3ee' : '#f8fafc'}
                    anchorX="center"
                    anchorY="top"
                    maxWidth={3}
                    textAlign="center"
                >
                    {item.title}
                </Text>
            </Float>
        </group>
    )
}

/**
 * Scene Content with performance-optimized auto-scroll
 */
const SceneContent: React.FC<{ items: ProductItem[]; isPaused: boolean; onHover: (h: boolean) => void }> = ({ items, isPaused, onHover }) => {
    const gap = 5
    const scrollOffset = useRef(0)
    const { camera } = useThree()

    useFrame((state, delta) => {
        if (!isPaused) {
            scrollOffset.current += delta * 0.02
            if (scrollOffset.current > 1) scrollOffset.current -= 1
        }

        // Camera breathing
        camera.position.x = THREE.MathUtils.lerp(camera.position.x, Math.sin(state.clock.elapsedTime * 0.3) * 0.2, 0.05)
        camera.position.y = THREE.MathUtils.lerp(camera.position.y, Math.sin(state.clock.elapsedTime * 0.2) * 0.1, 0.05)
    })

    return (
        <Bvh firstHitOnly>
            <group position={[0, 0, 0]}>
                <Suspense fallback={null}>
                    {items.map((item, i) => (
                        <ProductCard
                            key={`${item.id}-${i}`}
                            item={item}
                            index={i}
                            total={items.length}
                            gap={gap}
                            scrollOffset={scrollOffset}
                            isPaused={isPaused}
                            onHover={onHover}
                        />
                    ))}
                </Suspense>

                {/* Optimized Ground Plane */}
                <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -4, 0]}>
                    <planeGeometry args={[100, 100]} />
                    <meshStandardMaterial color="#020617" metalness={0.8} roughness={0.4} />
                </mesh>

                {/* Efficient Particles */}
                <Sparkles 
                    count={50} 
                    scale={20} 
                    size={2} 
                    speed={0.2} 
                    opacity={0.3} 
                    color="#22d3ee" 
                />
            </group>
        </Bvh>
    )
}

/**
 * Main Optimized 3D Showcase Component
 * Features:
 * - next/image style texture optimization
 * - Reduced draw calls via drei/Image
 * - Adaptive performance scaling
 * - Infinite auto-scroll
 */
const InfiniteProductsShowcase: React.FC<InfiniteProductsShowcaseProps> = ({ items }) => {
    const [isPaused, setIsPaused] = useState(false)

    if (!items || items.length === 0) return null

    return (
        <div className="w-full h-[550px] relative bg-[#020617] overflow-hidden group/canvas">
            <Canvas
                shadows={false}
                gl={{ 
                    antialias: true,
                    powerPreference: "high-performance",
                    stencil: false,
                    depth: true
                }}
                dpr={[1, 1.5]}
                camera={{ position: [0, 0, 12], fov: 35 }}
            >
                <color attach="background" args={['#020617']} />
                
                {/* Lighting */}
                <ambientLight intensity={0.5} />
                <pointLight position={[10, 10, 10]} intensity={1} color="#22d3ee" />
                <pointLight position={[-10, -10, -10]} intensity={0.5} color="#3b82f6" />
                <Environment preset="night" />

                <SceneContent items={items} isPaused={isPaused} onHover={setIsPaused} />
                
                {/* Performance Helpers */}
                <AdaptiveDpr pixelated />
                <AdaptiveEvents />
                <Preload />
            </Canvas>

            {/* Overlay Instructions */}
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 pointer-events-none transition-opacity duration-500 opacity-60 group-hover/canvas:opacity-100">
                <div className="px-4 py-2 bg-slate-900/50 backdrop-blur-md rounded-full border border-slate-800 text-cyan-400 text-[10px] font-mono tracking-[0.2em] uppercase flex items-center gap-3">
                    <span className="relative flex h-2 w-2">
                        <span className={`animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75 ${isPaused ? 'hidden' : ''}`}></span>
                        <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-500"></span>
                    </span>
                    {isPaused ? 'Duraklatıldı • Ürünleri Keşfet' : 'Otomatik Akış • Durdurmak İçin Bekle'}
                </div>
            </div>

            {/* Cinematic Gradient Masking */}
            <div className="absolute inset-y-0 left-0 w-32 bg-gradient-to-r from-[#020617] via-[#020617]/40 to-transparent pointer-events-none" />
            <div className="absolute inset-y-0 right-0 w-32 bg-gradient-to-l from-[#020617] via-[#020617]/40 to-transparent pointer-events-none" />
        </div>
    )
}

export default InfiniteProductsShowcase
