/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
import React from 'react'
import Image from 'next/image'
import { Search } from 'lucide-react'
import { useI18n } from '../../i18n/I18nProvider'

interface ProductsHeroProps {
    searchValue: string
    onSearchChange: (value: string) => void
    searchInputRef?: React.RefObject<HTMLInputElement>
}

/**
 * Products Hub Hero Section - Optimized for LCP
 * Dark navy gradient with industrial background image and white search bar
 */
const ProductsHero: React.FC<ProductsHeroProps> = ({
    searchValue,
    onSearchChange,
    searchInputRef
}) => {
    const { t } = useI18n()

    return (
        <section className="relative min-h-[320px] rounded-2xl overflow-hidden bg-surface-navy">
            {/* Background Image - Optimized for LCP */}
            <div className="absolute inset-0 z-0">
                <Image
                    src="/images/modern-industrial-HVAC-rooftop-blue-sky-facility.jpg"
                    alt={t('products.heroAlt') || 'Industrial HVAC Systems'}
                    fill
                    sizes="(max-width: 1280px) 100vw, 1280px"
                    className="object-cover opacity-20"
                />
                {/* Gradient Overlay to maintain brand colors and readability */}
                <div className="absolute inset-0 bg-gradient-to-b from-surface-navy/80 via-surface-navy-mid/90 to-surface-navy" />
            </div>

            {/* Background Pattern - Decorative SVGs */}
            <div className="absolute inset-0 overflow-hidden pointer-events-none opacity-40">
                {/* Grid Pattern */}
                <svg className="absolute inset-0 w-full h-full" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                    <defs>
                        <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                            <path d="M 40 0 L 0 0 0 40" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="1" />
                        </pattern>
                    </defs>
                    <rect width="100%" height="100%" fill="url(#grid)" />
                </svg>

                {/* Diagonal Lines - Decorative elements */}
                <svg className="absolute top-0 right-0 w-80 h-80 opacity-20" viewBox="0 0 200 200" fill="none" aria-hidden="true">
                    <line x1="50" y1="0" x2="200" y2="150" stroke="white" strokeWidth="1" />
                    <line x1="80" y1="0" x2="200" y2="120" stroke="white" strokeWidth="1" />
                    <line x1="110" y1="0" x2="200" y2="90" stroke="white" strokeWidth="1" />
                    <line x1="140" y1="0" x2="200" y2="60" stroke="white" strokeWidth="1" />
                </svg>
            </div>

            {/* Content Container */}
            <div className="relative z-10 px-8 py-16 md:py-24 flex flex-col items-center justify-center text-center">
                {/* Title */}
                <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-8 tracking-tight max-w-3xl drop-shadow-md">
                    {t('products.hubTitle') || 'Profesyonel HVAC Çözümleri'}
                </h1>

                {/* Search Bar Container */}
                <div className="w-full max-w-xl mx-auto px-4">
                    <div className="relative group">
                        <div className="absolute inset-0 bg-white/10 blur-xl rounded-2xl group-focus-within:bg-cyan-400/10 transition-colors" />
                        <div className="relative flex items-center bg-white rounded-xl shadow-2xl overflow-hidden transition-colors focus-within:ring-2 focus-within:ring-cyan-400/50">
                            <Search className="absolute left-4 text-gray-400 group-focus-within:text-cyan-500 transition-colors" size={20} aria-hidden="true" />
                            <input
                                ref={searchInputRef}
                                type="search"
                                value={searchValue}
                                onChange={(e) => onSearchChange(e.target.value)}
                                placeholder={t('products.searchPlaceholder') || 'Ürün veya kategori arayın...'}
                                aria-label={t('products.searchAriaLabel') || 'Ürün ara'}
                                className="w-full pl-12 pr-6 py-4 bg-transparent text-gray-800 placeholder-gray-400 border-0 focus:outline-none text-base md:text-lg"
                            />
                        </div>
                    </div>
                    {/* Optional Help Text */}
                    <p className="mt-4 text-white/50 text-sm">
                        {t('products.searchHelp') || 'Binlerce ürün arasında hızlıca bulun'}
                    </p>
                </div>
            </div>
        </section>
    )
}

export default ProductsHero
