/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
import React from 'react'

import { useFanMaterials } from '../../materials/useFanMaterials'

interface BoxAndBaseProps {
    isSelected?: boolean
    isIsolated?: boolean
    isHidden?: boolean
    onClick?: () => void
    explode?: number
}

const BoxAndBase: React.FC<BoxAndBaseProps> = ({
    isSelected,
    isIsolated,
    isHidden,
    onClick,
    explode = 0
}) => {
    const materials = useFanMaterials()

    if (isHidden || (isIsolated === false)) return null

    const boxMaterial = isSelected ? materials.safetyOrange : materials.matteBlack

    return (
        <group 
            onClick={(e) => {
                e.stopPropagation()
                onClick?.()
            }}
        >
            {/* Junction Box */}
            <mesh position={[0, 0.15 + (explode * 0.2), 0]} material={boxMaterial} castShadow>
                <boxGeometry args={[0.12, 0.08, 0.1]} />
            </mesh>

            {/* Mounting Base */}
            <mesh position={[0, -0.15 - (explode * 0.2), 0]} material={materials.matteBlack} receiveShadow>
                <boxGeometry args={[0.2, 0.02, 0.15]} />
            </mesh>
        </group>
    )
}

export default BoxAndBase
