/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
import React from 'react'

import { useFanMaterials } from '../../materials/useFanMaterials'

interface GreenClampsProps {
    isSelected?: boolean
    isIsolated?: boolean
    isHidden?: boolean
    onClick?: () => void
    explode?: number
}

const GreenClamps: React.FC<GreenClampsProps> = ({
    isSelected,
    isIsolated,
    isHidden,
    onClick,
    explode = 0
}) => {
    const materials = useFanMaterials()

    if (isHidden || (isIsolated === false)) return null

    const clampMaterial = isSelected ? materials.safetyOrange : materials.vorticeGreen

    return (
        <group 
            onClick={(e) => {
                e.stopPropagation()
                onClick?.()
            }}
        >
            {/* Left Clamp */}
            <mesh position={[-0.2 - (explode * 0.1), 0, 0]} material={clampMaterial} castShadow>
                <torusGeometry args={[0.12, 0.015, 16, 32]} />
            </mesh>

            {/* Right Clamp */}
            <mesh position={[0.2 + (explode * 0.1), 0, 0]} material={clampMaterial} castShadow>
                <torusGeometry args={[0.12, 0.015, 16, 32]} />
            </mesh>
        </group>
    )
}

export default GreenClamps
