/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { useFanMaterials } from '../../materials/useFanMaterials'

interface InternalFanRotorProps {
    radius?: number
    spinSpeed?: number
    position?: [number, number, number]
    rotation?: [number, number, number]
    isSelected?: boolean
    isIsolated?: boolean
    isHidden?: boolean
    onClick?: () => void
    explode?: number
}

const InternalFanRotor: React.FC<InternalFanRotorProps> = ({
    radius = 0.25,
    spinSpeed = 10,
    position = [0, 0, 0],
    rotation = [0, 0, 0],
    isSelected,
    isIsolated,
    isHidden,
    onClick,
    explode = 0
}) => {
    const groupRef = useRef<THREE.Group>(null)
    const materials = useFanMaterials()
    const bladeCount = 6

    useFrame((_, delta) => {
        if (groupRef.current && !isHidden && isIsolated !== false) {
            groupRef.current.rotation.y += delta * (isSelected ? 0 : spinSpeed)
        }
    })

    if (isHidden || (isIsolated === false)) return null

    const bladeMaterial = isSelected ? materials.safetyOrange : materials.vorticeGreen

    return (
        <group 
            position={position} 
            rotation={rotation}
            onClick={(e) => {
                e.stopPropagation()
                onClick?.()
            }}
        >
            <group ref={groupRef}>
                <mesh material={materials.matteBlack} castShadow>
                    <cylinderGeometry args={[radius * 0.22, radius * 0.22, 0.08, 16]} />
                </mesh>
                
                <mesh position={[0, 0.04, 0]} material={materials.matteBlack} castShadow>
                    <sphereGeometry args={[radius * 0.22, 16, 16, 0, Math.PI * 2, 0, Math.PI / 2]} />
                </mesh>

                {Array.from({ length: bladeCount }).map((_, i) => (
                    <group key={i} rotation={[0, (i * Math.PI * 2) / bladeCount, 0]}>
                        <mesh 
                            position={[radius * 0.58 + (explode * 0.1), 0, 0]} 
                            rotation={[0.4, 0, 0.05]} 
                            material={bladeMaterial}
                            castShadow
                            receiveShadow
                        >
                            <boxGeometry args={[radius * 0.75, 0.012, radius * 0.35]} />
                        </mesh>
                    </group>
                ))}
            </group>
        </group>
    )
}

export default InternalFanRotor
