/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
import React from 'react';

interface DividerProps {
  /**
   * Optional text to display within the divider.
   */
  label?: string;
  /**
   * Position of the label within the divider.
   * @default 'center'
   */
  labelPosition?: 'left' | 'center' | 'right';
  /**
   * Additional CSS classes for the container.
   */
  className?: string;
}

/**
 * Divider component with an industrial-gray aesthetic for VentHub HVAC systems.
 * Provides a clean, thin separation line with optional label support.
 */
export function Divider({ 
  label, 
  labelPosition = 'center', 
  className = '' 
}: DividerProps) {
  const baseLineStyles = "h-px bg-zinc-200 w-full";
  
  if (!label) {
    return (
      <div 
        className={`w-full py-4 ${className}`} 
        role="separator" 
        aria-orientation="horizontal"
      >
        <div className={baseLineStyles} />
      </div>
    );
  }

  const labelAlignment = {
    left: 'justify-start',
    center: 'justify-center',
    right: 'justify-end'
  };

  return (
    <div 
      className={`relative flex items-center w-full py-4 ${labelAlignment[labelPosition]} ${className}`}
      role="separator" 
      aria-orientation="horizontal"
    >
      <div className="absolute inset-0 flex items-center" aria-hidden="true">
        <div className={baseLineStyles} />
      </div>
      <div className="relative flex justify-center bg-white px-3">
        <span className="text-xs font-medium uppercase tracking-wider text-zinc-500">
          {label}
        </span>
      </div>
    </div>
  );
}
