/** @generated by VentHub-Subagent - DO NOT EDIT MANUALLY **/
'use client'

import Link from 'next/link'
import React from 'react'

import { resolveProductImageUrl } from '@/lib/images/productImage'
import type { WithDisplayPrice } from '@/lib/services/displayPrice.service'
import type { Product } from '@/types/ui-models'

import { useCart } from '../hooks/useCartHook'
import { useLocalizedRoutes } from '../hooks/useLocalizedRoutes'
import { formatCurrency } from '../i18n/format'
import { useI18n } from '../i18n/I18nProvider'
import { BrandIcon } from './HVACIcons'
import VentImage from './ui/VentImage'

/**
 * W4b · Kartın fiyat kaynağı MOTORDUR (`displayPrice`), ham `products.price` DEĞİL —
 * o kolon Kademe-2'de emekli edildi (INV-PRICE-1, cetvel §1).
 *
 * Alanlar bilinçli olarak OPSİYONEL: fiyat köprüsü henüz bağlanmamış çağıranlar
 * (ör. ana sayfa blokları) derlenmeye devam etsin, ama fiyat yerine "Teklif İste"
 * göstersin. Yanlış fiyat göstermek, fiyat göstermemekten kötüdür.
 */
export type StorefrontProduct = Product &
  Partial<Pick<WithDisplayPrice<Product>, 'displayPrice' | 'displayPriceTaxIncluded'>>

interface ProductCardProps {
  product: StorefrontProduct
  onQuickView?: (product: StorefrontProduct) => void
  highlightFeatured?: boolean
  layout?: 'grid' | 'list'
  priority?: boolean
  hidePrice?: boolean
  compact?: boolean
}

const ProductCard: React.FC<ProductCardProps> = React.memo(function ProductCard({
  product,
  layout = 'grid',
  priority = false,
  hidePrice = false,
  compact = false
}) {
  const { lang, t } = useI18n()
  const Routes = useLocalizedRoutes()
  const isList = layout === 'list'
  const { addToCart } = useCart()

  const displayPrice = product.displayPrice ?? null

  /**
   * İKİ AYRI SORU, İKİ AYRI DEĞİŞKEN — eskiden `quoteMode` ikisini birbirine yapıştırıyordu
   * (`hidePrice || fiyat yok`), bu yüzden fiyatı GİZLEMEK istemek sepete eklemeyi de
   * kapatıyordu. Ticari karar "fiyatı kartta gösterme" idi, "karttan satın almayı kaldır"
   * değil; ikisi ayrılmazsa görsel bir tercih sessizce satış yolunu kapatır.
   *
   *  · quoteMode  = SATIN ALINABİLİR Mİ  → fiyat yoksa "Teklif İste", sepet kapalı
   *  · showPrice  = GÖSTERİLECEK Mİ      → çağıran `hidePrice` ile bastırabilir
   *
   * Recep kararı (2026-08-15): fiyat yalnız ürün satış sayfasında (PDP) görünür; kartlar
   * bastırır. Cetvel gerekçesi PS-042 (`product-schema-standard.md` §2.2): kart fiyat
   * taşımazsa keşif önbelleği de taşımaz, fiyat değişimi keşif'i çökertmek zorunda kalmaz.
   */
  const quoteMode = displayPrice == null || displayPrice <= 0
  const showPrice = !hidePrice && !quoteMode

  // KDV etiketi ARTIK SABİT DEĞİL: bireysel/anon BRÜT (KDV dahil), bayi/kurumsal NET görür.
  // Semantik bilinmiyorsa (fiyat köprüsü bağlı değil) etiket HİÇ çizilmez — bayiye "KDV Dahil"
  // demek, hiçbir şey dememekten kötüdür (net fiyatı brüt sanıp eksik teklif verir).
  // Anahtarlar İKİ AYRI t() çağrısı: `t(cond ? 'a' : 'b')` biçimini INV-5 keycheck'i
  // göremez, eksik anahtar sessizce ham-key render ederdi.
  const taxIncluded = product.displayPriceTaxIncluded ?? null
  const taxLabel = taxIncluded == null ? null : taxIncluded ? t('pdp.vatIncluded') : t('pdp.vatExcluded')

  const handleAddToCart = (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    if (quoteMode) return
    addToCart(product)
  }

  // LIST VIEW LAYOUT
  if (isList) {
    return (
      <Link href={Routes.product(product.slug!)} className="block w-full">
        <div className="group relative flex items-center bg-white rounded-2xl border border-light-gray p-4 transition-transform duration-300 hover:shadow-hvac-lg hover:-translate-y-0.5 overflow-hidden">
          <div className="relative w-28 h-28 sm:w-32 sm:h-32 flex-shrink-0 bg-light-gray/50 rounded-xl overflow-hidden p-2">
            <VentImage
              src={resolveProductImageUrl(product)}
              alt={product.name}
              fallbackType="product"
              fill
              sizes="128px"
              className="object-contain p-2 transition-transform duration-500 group-hover:scale-105"
            />
          </div>
          
          <div className="ml-5 flex-1 flex flex-col justify-center min-w-0">
            <div className="flex items-center space-x-2 mb-1">
              <span className="text-xs font-bold uppercase tracking-wider text-secondary-blue">{product.brand}</span>
              <span className="text-xs text-steel-gray">/</span>
              <span className="text-xs text-steel-gray font-medium truncate">{product.sku}</span>
            </div>
            <h3 className="text-base sm:text-lg font-bold text-industrial-gray group-hover:text-primary-navy transition-colors line-clamp-1">
              {product.name}
            </h3>
            <div className="mt-2 flex items-baseline gap-3">
              <div className="text-xl font-bold text-primary-navy">
                {showPrice ? (
                  formatCurrency(displayPrice ?? 0, lang, { currency: 'TRY', maximumFractionDigits: 0 })
                ) : (
                  <span className="text-sm font-medium text-industrial-gray">{t('common.requestQuote')}</span>
                )}
              </div>
              {showPrice && taxLabel && <span className="text-xs text-steel-gray font-medium uppercase">{taxLabel}</span>}
            </div>
          </div>

          <button
            onClick={handleAddToCart}
            disabled={quoteMode}
            aria-disabled={quoteMode}
            className="focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-navy focus-visible:ring-offset-2 w-11 h-11 rounded-xl bg-primary-navy text-white flex items-center justify-center hover:bg-secondary-blue transition-transform shadow-md active:scale-95 ml-4 flex-shrink-0 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-primary-navy"
            title={quoteMode ? t('common.requestQuote') : t('common.addToCart')}
          >
            <svg width={20} height={20} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v16m8-8H4" />
            </svg>
          </button>
        </div>
      </Link>
    )
  }

  // GRID VIEW
  return (
    <Link href={Routes.product(product.slug!)} className="block h-full">
      <div className={`group relative flex flex-col h-full bg-white rounded-2xl border border-light-gray transition-transform duration-300 hover:shadow-hvac-lg hover:-translate-y-1 overflow-hidden ${compact ? 'p-3' : 'p-4'}`}>
        
        {/* Badges Overlay */}
        <div className="absolute top-3 left-3 right-3 z-20 flex justify-between items-start pointer-events-none">
          {product.is_featured && (
            <div className="bg-gold-accent backdrop-blur-sm text-white text-xs font-bold uppercase tracking-wider px-2 py-1 rounded shadow-sm">
              {t('pdp.featured') || 'ÖNE ÇIKAN'}
            </div>
          )}
          <div className="bg-white/90 backdrop-blur-sm rounded-lg p-1 border border-light-gray shadow-sm opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <BrandIcon brand={product.brand} />
          </div>
        </div>

        {/* Product Image */}
        <div className="relative aspect-square w-full rounded-xl overflow-hidden bg-light-gray/30 mb-4 group-hover:bg-light-gray/50 transition-colors">
          <VentImage
            src={resolveProductImageUrl(product)}
            alt={product.name}
            fallbackType="product"
            fill
            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 300px"
            className="object-contain transition-transform duration-500 group-hover:scale-105 p-6"
            priority={priority}
          />
        </div>

        {/* Product Details */}
        <div className="flex flex-col flex-1 px-1">
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-xs font-bold uppercase tracking-wider text-secondary-blue">
              {product.brand}
            </span>
            <span className="text-xs text-steel-gray font-medium">{product.sku}</span>
          </div>
          
          <h3 className="text-sm font-bold text-industrial-gray leading-snug min-h-10 line-clamp-2 mb-4 group-hover:text-primary-navy transition-colors">
            {product.name}
          </h3>

          <div className="mt-auto pt-3 border-t border-light-gray flex items-center justify-between">
            <div className="flex flex-col">
              <div className="text-lg font-bold text-primary-navy tracking-tight">
                {showPrice ? (
                  formatCurrency(displayPrice ?? 0, lang, { currency: 'TRY', maximumFractionDigits: 0 })
                ) : (
                  <span className="text-xs font-semibold text-industrial-gray">{t('common.requestQuote')}</span>
                )}
              </div>
              {/* Izgara kartında KDV etiketi BİLİNÇLİ olarak yok: master'da da yoktu.
                  Eklemek kart yüksekliğini fiyatlı/fiyatsız ürünlerde farklılaştırır —
                  vitrin kart ritmi storefront-design-standard kapsamında, tek başına
                  alınacak bir karar değil. */}
            </div>

            <button
              onClick={handleAddToCart}
              disabled={quoteMode}
              aria-disabled={quoteMode}
              className="focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-navy focus-visible:ring-offset-2 w-9 h-9 rounded-lg bg-primary-navy text-white flex items-center justify-center transition-transform hover:bg-secondary-blue hover:shadow-lg active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-primary-navy"
              title={quoteMode ? t('common.requestQuote') : t('common.addToCart')}
            >
              <svg width={18} height={18} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v16m8-8H4" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </Link>
  )
})

export default ProductCard
