name: CI

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --prefer-offline

      - name: Type check
        run: pnpm exec tsc -b tsconfig.build.json

      - name: Lint (non-blocking warnings)
        run: pnpm exec eslint . --ext .ts,.tsx || true

      - name: Unit tests (stable subset)
        run: pnpm exec vitest run src/pages/checkout/__tests__/buildPaymentRequest.test.ts src/pages/checkout/__tests__/ReviewSummary.test.tsx src/pages/account/__tests__/AccountSecurityPage.test.tsx --run

      - name: Production build
        run: pnpm run build:ci

