name: DB Advisor

on:
  push:
  pull_request:

jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Supabase Advisor (security + performance)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ] || [ -z "$SUPABASE_PROJECT_REF" ]; then
            echo "::notice title=Supabase Advisor::Secrets not set (SUPABASE_ACCESS_TOKEN / SUPABASE_PROJECT_REF). Skipping advisor checks."
            exit 0
          fi
          echo "::group::Advisor (security)"
          echo "Advisor integration placeholder. We'll wire Management API calls once secrets are set."
          echo "::endgroup::"
          echo "::group::Advisor (performance)"
          echo "Advisor integration placeholder. We'll wire Management API calls once secrets are set."
          echo "::endgroup::"
        continue-on-error: true
