name: DB Advisor

on:
  push:
  pull_request:

jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Supabase Advisor (security)
        uses: supabase-community/advisor-action@v1
        with:
          type: security
        continue-on-error: true

      - name: Supabase Advisor (performance)
        uses: supabase-community/advisor-action@v1
        with:
          type: performance
        continue-on-error: true
