name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required Cloudflare secrets
        run: |
          if [ -z "${{ secrets.CF_API_TOKEN }}" ] || [ -z "${{ secrets.CF_ACCOUNT_ID }}" ] || [ -z "${{ secrets.CF_PAGES_PROJECT_NAME }}" ]; then
            echo "::error::Missing Cloudflare secrets. Please set CF_API_TOKEN, CF_ACCOUNT_ID, CF_PAGES_PROJECT_NAME."
            exit 1
          fi

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          VITE_CART_SERVER_SYNC: "true"
          VITE_COMMIT_SHA: "${{ github.sha }}"
          VITE_BRANCH: "${{ github.ref_name }}"
        run: pnpm run build:ci

      - name: Ensure Cloudflare Pages project exists (idempotent)
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: ${{ secrets.CF_PAGES_PROJECT_NAME }}
        run: |
          set -e
          # Try to create project; ignore error if it already exists
          RESP=$(curl -s -X POST \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"$CF_PAGES_PROJECT_NAME\",\"production_branch\":\"master\"}" \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects" || true)
          echo "Create project response: $RESP"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PAGES_PROJECT_NAME }}
          directory: dist
          branch: master
