name: Smoke CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  deno-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Format check (functions)
        run: deno fmt --check supabase/functions
      - name: Lint (functions)
        run: deno lint supabase/functions