name: Supabase Migrate

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Apply SQL migrations to Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "::error::SUPABASE_DB_URL secret is not set. Please add it in repo Settings > Secrets and variables > Actions."
            exit 1
          fi
          set -e
          for f in supabase/migrations/*.sql; do
            echo "Applying $f"
            psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
          echo "Migrations applied successfully."

