name: Supabase Migrate

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if required secrets are missing
        if: ${{ env.SUPABASE_ACCESS_TOKEN == '' || env.SUPABASE_PROJECT_REF == '' }}
        run: |
          echo "::error::Missing secrets. Please set SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF in repository secrets."
          exit 1

      - name: Setup Supabase CLI (pinned)
        uses: supabase/setup-cli@v1
        with:
          version: v2.39.2

      - name: Show CLI version and project ref
        run: |
          supabase --version
          echo "Project ref: $SUPABASE_PROJECT_REF"
          echo "Migrations in repo:" && ls -la supabase/migrations || true

      - name: Link project (debug)
        run: |
          set -e
          supabase link --project-ref "$SUPABASE_PROJECT_REF" --debug

      - name: Apply migrations via Supabase CLI (debug)
        run: |
          set -e
          supabase db push --debug
          echo "Migrations applied successfully via Supabase CLI."
