name: Supabase Migrate

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

concurrency:
  group: supabase-migrate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if DB URL missing
        run: |
          if [ -z "${SUPABASE_DB_URL}" ]; then
            echo "::error::Missing SUPABASE_DB_URL. Set it in repository secrets."
            exit 1
          fi

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Show target and list migrations
        run: |
          echo "Migrations in repo:" && ls -1 supabase/migrations || true
          # Host mask (do not print full URL)
          echo "Target host: $(echo "$SUPABASE_DB_URL" | sed -E 's|.*@([^:/]+).*|\1|')"

      - name: Normalize DB URL (enforce sslmode=require)
        run: |
          if echo "$SUPABASE_DB_URL" | grep -q "sslmode="; then
            DB_URL="$SUPABASE_DB_URL"
          else
            if echo "$SUPABASE_DB_URL" | grep -q "?"; then
              DB_URL="${SUPABASE_DB_URL}&sslmode=require"
            else
              DB_URL="${SUPABASE_DB_URL}?sslmode=require"
            fi
          fi
          echo "DB_URL=$DB_URL" >> $GITHUB_ENV

      - name: Test DB connection
        run: |
          psql "$DB_URL" -c "select 1;"

      - name: Apply migrations via psql (psql-only)
        run: |
          set -e
          shopt -s nullglob
          files=(supabase/migrations/*.sql)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No migrations to apply."
            exit 0
          fi
          for f in $(ls -1 supabase/migrations/*.sql | sort); do
            echo "Applying $f"
            psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
          echo "Migrations applied successfully via psql."
