name: Supabase Migrate

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

concurrency:
  group: supabase-migrate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decide execution path (prefer psql for stability)
        run: |
          if [ -n "${SUPABASE_DB_URL}" ]; then
            echo "Will use psql with SUPABASE_DB_URL (sslmode=require)."
            exit 0
          fi
          if [ -n "${SUPABASE_ACCESS_TOKEN}" ] && [ -n "${SUPABASE_PROJECT_REF}" ]; then
            echo "DB_URL missing — fallback to Supabase CLI with ACCESS_TOKEN + PROJECT_REF."
            exit 0
          fi
          echo "::error::Missing configuration. Set SUPABASE_DB_URL (preferred), or SUPABASE_ACCESS_TOKEN + SUPABASE_PROJECT_REF as fallback."
          exit 1

      - name: Install PostgreSQL client
        if: ${{ env.SUPABASE_DB_URL != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Show target and list migrations
        run: |
          echo "Migrations in repo:" && ls -1 supabase/migrations || true
          # Host mask (do not print full URL)
          echo "Target host: $(echo "$SUPABASE_DB_URL" | sed -E 's|.*@([^:/]+).*|\1|')"

      - name: Normalize DB URL (enforce sslmode=require)
        if: ${{ env.SUPABASE_DB_URL != '' }}
        run: |
          if echo "$SUPABASE_DB_URL" | grep -q "sslmode="; then
            DB_URL="$SUPABASE_DB_URL"
          else
            if echo "$SUPABASE_DB_URL" | grep -q "?"; then
              DB_URL="${SUPABASE_DB_URL}&sslmode=require"
            else
              DB_URL="${SUPABASE_DB_URL}?sslmode=require"
            fi
          fi
          echo "DB_URL=$DB_URL" >> $GITHUB_ENV

      - name: Test DB connection
        if: ${{ env.SUPABASE_DB_URL != '' }}
        run: |
          psql "$DB_URL" -c "select 1;"

      - name: Apply migrations via psql
        if: ${{ env.SUPABASE_DB_URL != '' }}
        run: |
          set -e
          shopt -s nullglob
          files=(supabase/migrations/*.sql)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No migrations to apply."
            exit 0
          fi
          for f in $(ls -1 supabase/migrations/*.sql | sort); do
            echo "Applying $f"
            psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$f" || echo "Warning: $f may have already been applied"
          done
          echo "Migrations applied successfully via psql."

