name: Supabase Migrate

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**.sql'
  workflow_dispatch:

concurrency:
  group: supabase-migrate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if required secrets are missing
        if: ${{ env.SUPABASE_ACCESS_TOKEN == '' || env.SUPABASE_PROJECT_REF == '' }}
        run: |
          echo "::error::Missing secrets. Please set SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF in repository secrets."
          exit 1

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        continue-on-error: true
        with:
          version: latest

      - name: Show CLI version and project ref
        if: always()
        run: |
          (supabase --version || echo "supabase CLI not available")
          echo "Project ref: $SUPABASE_PROJECT_REF"
          echo "Migrations in repo:" && ls -la supabase/migrations || true

      - name: Diagnose Supabase project visibility
        if: always()
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -e
          echo "Listing projects via API to verify visibility..."
          RESP=$(curl -s -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" https://api.supabase.com/v1/projects || true)
          echo "$RESP" > projects.json
          echo "Projects JSON fetched (length): $(wc -c < projects.json || echo 0)"
          echo "Does the ref appear? ($SUPABASE_PROJECT_REF)"
          if echo "$RESP" | grep -q '"ref":"'$SUPABASE_PROJECT_REF'"'; then
            echo "OK: Project ref $SUPABASE_PROJECT_REF is visible to this token."
          else
            echo "::warning::Project ref $SUPABASE_PROJECT_REF not found in token's project list. Check token account/org."
          fi

      - name: Link project (debug)
        if: always()
        run: |
          set -e
          if ! command -v supabase >/dev/null 2>&1; then
            echo "supabase CLI not installed; skipping link"
            exit 0
          fi
          supabase link --project-ref "$SUPABASE_PROJECT_REF" --debug || exit 1

      - name: Apply migrations via Supabase CLI (debug)
        if: always()
        run: |
          set -e
          if ! command -v supabase >/dev/null 2>&1; then
            echo "supabase CLI not installed; skipping db push"
            exit 0
          fi
          supabase db push --debug
          echo "Migrations applied successfully via Supabase CLI."

      - name: Install PostgreSQL client (fallback)
        if: always()
        run: |
          if [ -z "${SUPABASE_DB_URL}" ]; then
            echo "No SUPABASE_DB_URL provided; skipping psql fallback install"
            exit 0
          fi
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Apply migrations via psql (fallback)
        if: always()
        run: |
          if [ -z "${SUPABASE_DB_URL}" ]; then
            echo "No SUPABASE_DB_URL provided; skipping psql fallback"
            exit 0
          fi
          set -e
          for f in supabase/migrations/*.sql; do
            echo "Applying $f"
            psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
          echo "Migrations applied via psql fallback."
