name: Verify Cart Items (unit_price + price_list_id)

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      minutes:
        description: "Look back window in minutes"
        required: false
        default: "30"
      email:
        description: "Optional user email to filter"
        required: false
        default: ""

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL || secrets.VITE_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install supabase-js
        run: |
          npm -v
          npm init -y >/dev/null 2>&1
          npm i @supabase/supabase-js@2 >/dev/null 2>&1

      - name: Query recent cart_items
        env:
          MINUTES: ${{ github.event.inputs.minutes }}
          EMAIL: ${{ github.event.inputs.email }}
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const url = process.env.SUPABASE_URL;
          const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
          if (!url || !key) { console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY'); process.exit(1); }
          const supabase = createClient(url, key);
          (async () => {
            let query = supabase.from('cart_items')
              .select('id, cart_id, product_id, quantity, unit_price, price_list_id')
              .limit(100);
            if (process.env.EMAIL) {
              // Filter by user email via user_profiles + carts (fallback to just list all if not found)
              const { data: profiles, error: perr } = await supabase.from('user_profiles').select('id, email').eq('email', process.env.EMAIL).limit(1);
              if (perr) { console.log('Email filter failed, showing all'); } else if (!profiles || profiles.length === 0) { console.log('[]'); return; }
              else {
                const uid = profiles[0].id;
                const { data: carts, error: cerr } = await supabase.from('shopping_carts').select('id').eq('user_id', uid).limit(10);
                if (cerr) { console.log('Cart lookup failed, showing all'); } else {
                  const cartIds = (carts||[]).map(c => c.id);
                  if (cartIds.length === 0) { console.log('[]'); return; }
                  query = query.in('cart_id', cartIds);
                }
              }
            }
            const { data, error } = await query;
            if (error) throw error;
            const rows = (data||[]).map(r => ({ id:r.id, cart_id:r.cart_id, product_id:r.product_id, qty:r.quantity, unit_price:r.unit_price, price_list_id:r.price_list_id }));
            const nullPrices = rows.filter(r => r.unit_price == null).length;
            const summary = { count: rows.length, null_unit_price: nullPrices, rows };
            console.log(JSON.stringify(summary, null, 2));
            if (rows.length > 0 && nullPrices > 0) {
              console.error(`Found ${nullPrices} rows with null unit_price`);
              process.exit(2);
            }
          })().catch(e => { console.error(e); process.exit(1); });
          "

      - name: Summary
        if: success()
        run: |
          echo "Verification finished. Check the step logs above for JSON output (count + rows)."
